package model.enums;

public enum STATUS {
  SUCCESS, FAILED, USERNAME_INVALID, USERNAME_IN_USE, PASSWORD_INVALID, PLATE_INVALID, PLATE_DUPLICATE,
  NOT_LOGGED_IN, MEMBER_HAS_RESERVATION, NO_SPOTS_AVAILABLE, SPOT_NOT_FOUND, SPOT_RESERVED, INVALID_ID,
  PLATE_NOT_FOUND, INVALID_AMT, INSUFFICIENT_CREDITS, PASSWORD_REUSE
}
